global_configs= "-or_sz=1 -payload_sz=524288 -threads=1 -write_imm 0 -undefok=write_imm,or_sz "

[[pass]]
host = "val08"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./user_payload_trc_server -host_len=1 -threads=1 -port=8000 -write_imm=0'


[[pass]]
host = "val14"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./user_payload_trc_client -host=0 -or_sz=1 -threads=1 -addr=val08 -port=8000 -write_imm=0 -id=0'

