[[pass]]
host = "val09"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_server -host_len=11 -or_sz=2048 -threads=1 -run_sec=40 -port=1'


[[pass]]
host = "val01"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_client -vid=1 -or_sz=1 -threads=1 -run_sec=20 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7e00'


[[pass]]
host = "val02"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_client -vid=2 -or_sz=1 -threads=1 -run_sec=20 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7e00'
#
[[pass]]
host = "val03"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_client -vid=3 -or_sz=1 -threads=1 -run_sec=20 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7e00'
###
[[pass]]
host = "val04"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_client -vid=4 -or_sz=1 -threads=1 -run_sec=20 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7e00'
###
[[pass]]
host = "val05"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_client -vid=5 -or_sz=1 -threads=1 -run_sec=20 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7e00'

[[pass]]
host = "val06"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_client -vid=6 -or_sz=1 -threads=1 -run_sec=20 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7e00'
###
[[pass]]
host = "val07"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_client -vid=7 -or_sz=1 -threads=1 -run_sec=20 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7e00'
#
[[pass]]
host = "val08"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_client -vid=8 -or_sz=1 -threads=1 -run_sec=20 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7e00'


[[pass]]
host = "val12"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_client -vid=9 -or_sz=1 -threads=1 -run_sec=20 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7e00'


[[pass]]
host = "val14"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_client -vid=10 -or_sz=1 -threads=1 -run_sec=20 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7e00'
