[[pass]]
host = "val09"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_server -host_len=11 -or_sz=2048 -threads=12 -run_sec=15 -port=1'


[[pass]]
host = "val01"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_client -vid=1 -or_sz=5 -threads=12 -run_sec=10 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7e00'
