global_configs= "-or_sz=1 -payload_sz=64 -threads=1 -write_imm=0 -undefok=write_imm,or_sz "

[[pass]]
host = "val03"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./user_twosided_rc_server -host_len=12 -port=8000 -write_imm=0'


[[pass]]
host = "val04"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./user_twosided_rc_client -host=0 -addr=val03 -port=8000 -write_imm=0 -id=0'


[[pass]]
host = "val05"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./user_twosided_rc_client -host=1 -addr=val03 -port=8000 -write_imm=0 -id=1'


[[pass]]
host = "val06"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./user_twosided_rc_client -host=2 -addr=val03 -port=8000 -write_imm=0 -id=2'

[[pass]]
host = "val07"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./user_twosided_rc_client -host=3 -addr=val03 -port=8000 -write_imm=0 -id=3'

[[pass]]
host = "val08"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./user_twosided_rc_client -host=4 -addr=val03 -port=8000 -write_imm=0 -id=4'
