global_configs= "-threads=1 -payload_sz=1024 -port=1"


[[pass]]
host = "val08"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_zcpy_server -host_len=1 -or_sz=2048 -run_sec=15 -port=1'


[[pass]]
host = "val14"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./kernel_twosided_rc_zcpy_client -vid=1 -or_sz=1 -run_sec=10 -port=1 -gid=fe80:0000:0000:0000:248a:0703:009c:7c94'

