[[pass]]
host = "val03"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_server_sync -run_sec=30'


[[pass]]
host = "val01"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_client_sync -rdma_op=0 -or_sz=12 -threads=24 -run_sec=10 -addr=val03:8888 -payload_sz=8'
