[[pass]]
host = "val03"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_server_sync -run_sec=60'


[[pass]]
host = "val01"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_client_sync -rdma_op=0 -or_sz=12 -threads=12 -run_sec=30 -addr=val03:8888 -payload_sz=8'

[[pass]]
host = "val02"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_client_sync -rdma_op=0 -or_sz=12 -threads=12 -run_sec=30 -addr=val03:8888 -payload_sz=8'

[[pass]]
host = "val04"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_client_sync -rdma_op=0 -or_sz=12 -threads=12 -run_sec=30 -addr=val03:8888 -payload_sz=8'

[[pass]]
host = "val05"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_client_sync -rdma_op=0 -or_sz=12 -threads=12 -run_sec=30 -addr=val03:8888 -payload_sz=8'


[[pass]]
host = "val06"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_client_sync -rdma_op=0 -or_sz=12 -threads=12 -run_sec=30 -addr=val03:8888 -payload_sz=8'


[[pass]]
host = "val07"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_client_sync -rdma_op=0 -or_sz=12 -threads=12 -run_sec=30 -addr=val03:8888 -payload_sz=8'


[[pass]]
host = "val08"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_client_sync -rdma_op=0 -or_sz=12 -threads=12 -run_sec=30 -addr=val03:8888 -payload_sz=8'


[[pass]]
host = "val09"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_client_sync -rdma_op=0 -or_sz=12 -threads=12 -run_sec=30 -addr=val03:8888 -payload_sz=8'


[[pass]]
host = "val12"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_client_sync -rdma_op=0 -or_sz=12 -threads=12 -run_sec=30 -addr=val03:8888 -payload_sz=8'

[[pass]]
host = "val14"
path = ''
cmd = 'cd projects/krdmakit/exp; ./urc_client_sync -rdma_op=0 -or_sz=12 -threads=12 -run_sec=30 -addr=val03:8888 -payload_sz=8'



